version: '3.8'

services:
  flowz-backend:
    container_name: flowz-backend
    image: yinoni2212/flowz-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - GOOGLE_OAUTH_ID=${GOOGLE_OAUTH_ID}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATA_REDIS_SSL_ENABLED=true
    restart: always