spring.application.name=flowz-api-builder

# ?????? ????? ?-MongoDB
spring.data.mongodb.uri=${MONGODB_URL}

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

google.client.id=${GOOGLE_OAUTH_ID}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USER}
# ?? ??? ??: ?????? ??? ??? ?? ?????? ?????? ?? ????? ???!
# ??? ???? ?????? ?????? ???? ???, ?????? "????? ??-????" (2-Step Verification),
# ??? ????? "????? ????????" (App Password) ??????? ????? ???.
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=my_super_secret_key_that_should_be_long_and_stored_in_application_properties