spring.application.name=flowz-api-builder

# ?????? ????? ?-MongoDB
spring.data.mongodb.uri=${MONGODB_URL}

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

google.client.id=${GOOGLE_OAUTH_ID}
